diff --git a/programs/Makefile b/programs/Makefile
index 643ce14..fdb9e61 100644
--- a/programs/Makefile
+++ b/programs/Makefile
@@ -211,14 +211,8 @@ install: lz4
 	@echo Installing binaries in $(DESTDIR)$(bindir)
 	$(MAKE_DIR) $(DESTDIR)$(bindir)/ $(DESTDIR)$(man1dir)/
 	$(INSTALL_PROGRAM) lz4$(EXT) $(DESTDIR)$(bindir)/lz4$(EXT)
-	$(LN_SF) lz4$(EXT) $(DESTDIR)$(bindir)/lz4c$(EXT)
-	$(LN_SF) lz4$(EXT) $(DESTDIR)$(bindir)/lz4cat$(EXT)
-	$(LN_SF) lz4$(EXT) $(DESTDIR)$(bindir)/unlz4$(EXT)
 	@echo Installing man pages in $(DESTDIR)$(man1dir)
 	$(INSTALL_DATA) lz4.1 $(DESTDIR)$(man1dir)/lz4.1
-	$(LN_SF) lz4.1 $(DESTDIR)$(man1dir)/lz4c.1
-	$(LN_SF) lz4.1 $(DESTDIR)$(man1dir)/lz4cat.1
-	$(LN_SF) lz4.1 $(DESTDIR)$(man1dir)/unlz4.1
 	@echo lz4 installation completed
 
 .PHONY: uninstall
