#!/bin/sh

# bump: lz4-version /LZ4_VERSION="(.*)"/ https://github.com/lz4/lz4.git|semver:^1
LZ4_VERSION="1.10.0"

export ZOPEN_BUILD_LINE="STABLE"
export ZOPEN_STABLE_URL="https://github.com/lz4/lz4/archive/refs/tags/v${LZ4_VERSION}.tar.gz"
export ZOPEN_STABLE_DEPS="curl gzip make coreutils python"
export ZOPEN_BOOTSTRAP=skip
export ZOPEN_CONFIGURE=skip
export ZOPEN_INSTALL_OPTS="install POSIX_ENV=Yes PREFIX=\${ZOPEN_INSTALL_DIR}"   
export ZOPEN_NAME="lz4-${LZ4_VERSION}"
export ZOPEN_EXTRA_CPPFLAGS='-I../lib/'

rm -f "v${LZ4_VERSION}"
ln -s ${ZOPEN_NAME} "v${LZ4_VERSION}"

# Requires python3
zopen_init()
{
  echo ${ZOPEN_INSTALL_DIR}
  if ! type python3 >/dev/null ; then
    printError "needs python3"
  fi
  export PATH=${HOME}/.local/bin:$PATH
}

zopen_append_to_env()
{
cat <<ZZ
if [ ! -z "\$ZOPEN_IN_ZOPEN_BUILD" ]; then
  export ZOPEN_EXTRA_CFLAGS="\${ZOPEN_EXTRA_CFLAGS} -I\$PWD/include"
  export ZOPEN_EXTRA_CXXFLAGS="\${ZOPEN_EXTRA_CXXFLAGS} -I\$PWD/include"
  export ZOPEN_EXTRA_LDFLAGS="\${ZOPEN_EXTRA_LDFLAGS} -L\$PWD/lib"
  export ZOPEN_EXTRA_LIBS="\${ZOPEN_EXTRA_LIBS} -llz4"
fi
ZZ
}

zopen_check_results()
{
# Unfortunately, the tests that run do not appear to be self-checking
# So - for now just make sure that they don't crash
echo "actualFailures:0"
echo "expectedFailures:0"
echo "totalTests:1"
}

zopen_get_version()
{
./lz4 --version | awk ' { print $7; }' | tr -d 'v,'
}
