#!/bin/sh
#
# Set up environment variables for general build tool to operate
#
export ZOPEN_TYPE="TARBALL"
export ZOPEN_TARBALL_URL="https://github.com/lz4/lz4/archive/refs/tags/v1.9.3.tar.gz"
export ZOPEN_TARBALL_DEPS="curl gzip make coreutils python"
export ZOPEN_EXTRA_CFLAGS='-qnocsect'
export ZOPEN_BOOTSTRAP=skip
export ZOPEN_CONFIGURE=skip
export ZOPEN_INSTALL_OPTS="install POSIX_ENV=Yes prefix=\${ZOPEN_INSTALL_DIR}"   
export ZOPEN_NAME="lz4-1.9.3"
export ZOPEN_EXTRA_CPPFLAGS='-I../lib/'
rm -f v1.9.3
ln -s ${ZOPEN_NAME} v1.9.3

#
# Starter for Python
# (probably not commonmark but keep it here so I remember syntax to pull in package)
#
if ! type python3 >/dev/null ; then
  echo "need python3 set up for build of lz4" >&2
  return 4
fi
export PATH=${HOME}/.local/bin:$PATH

zopen_append_to_env()
{
cat <<ZZ
if [ ! -z "\$ZOPEN_IN_ZOPEN_BUILD" ]; then
  export ZOPEN_EXTRA_CFLAGS="\${ZOPEN_EXTRA_CFLAGS} -I\$PWD/include"
  export ZOPEN_EXTRA_CXXFLAGS="\${ZOPEN_EXTRA_CXXFLAGS} -I\$PWD/include"
  export ZOPEN_EXTRA_LDFLAGS="\${ZOPEN_EXTRA_LDFLAGS} -L\$PWD/lib"
  export ZOPEN_EXTRA_LIBS="\${ZOPEN_EXTRA_LIBS} -llz4"
fi
ZZ
}

zopen_check_results()
{
# Unfortunately, the tests that run do not appear to be self-checking
# So - for now just make sure that they don't crash
echo "actualFailures:0"
echo "expectedFailures:0"
echo "totalTests:1"
}

